Rooms = [
    "Terror 1","Terror 2","Terror 3","Terror 4","Terror 5","Terror 6","Terror 7","Terror 8","Terror 9","Terror 10","Terror 11","Terror 12","Terror 13","Terror 14","Terror 15","Terror 16","Terror 17","	Terror 18","Terror 19","Terror 20","Terror 21",	"Terror 22","Terror 23","Terror 24","Terror 25","Terror 26","Terror 27","Terror 28","Terror 29","Terror 30","Terror 31","Terror 32","Terror 33","Terror 34","Terror 35","Terror 36","Terror 37","Terror 38","Terror 39","Terror 40","Terror 41","Terror 42","Terror 43","Terror 44","Terror 45","Terror 46","Terror 47","Terror 48","Terror 49","Terror 50","Terror 51","Terror 52","Terror 53","Terror 54", "Terror 55", "Terror 56", "Terror 57", "Terror 58", "Terror 59"," Terror 60", "Terror 61", "Terror 62", "Terror 63", "Terror 64", "Terror 65", "Terror 66", "Terror 67", "Terror 68"," Terror 69", "Terror 70", "Terror 71", "Terror 72", "Terror 73", "Terror 74", "Terror 75", "Terror 76", "Terror 77", "Terror 78", "Terror 79", "Terror 80", "Terror 81", "Terror 82", "Terror 83", "Terror 84", "Terror 85", "Terror 86", "Terror 87", "Terror 88", "Terror 89", "Terror 90", "Terror 91", "Terror 92", "Terror 93", "Terror 94", "Terror 95", "Terror 96"," Terror 97", "Terror 98", "Terror 99", "Terror 100"
]





Descriptions = [
" A girl goes missing in the woods and her parents find only a decrepit and scary doll left behind. They soon learn that the doll is actually their daughter. And she’s alive",
" New residents to an old neighborhood are invited by their friendly neighbors to a Halloween party. The neighbors are vampires.",
" A family dog runs away from home. He returns a year later to the delight of his family. But there’s something different about him. Something demonic.", 
" A girl goes missing. Fifteen years later her parents get a call from her older self. But they listen in fear because they killed their daughter that dark night years ago.",
"A man reads a novel, soon realizing that the story is his very own — and according to the book, a killer is looming.",
"A scientist clones his family that died in an airplane crash — but soon learns the repercussions of playing God.",
"A man wakes up bound to an electric chair.",
"A man wakes up in a coffin next to a fresh dead body.",
"A woman wakes up to find her family gone and her doors and windows boarded up with no way to escape.",
"A man afraid of snakes is shipwrecked on an island covered with them.",
" Serial killers worldwide are connected by a dark web website.",
"The world’s population is overtaken by vampires — all except one little child.",
"A woman afraid of clowns is forced to work in a travelling circus.",
" An astronaut and cosmonaut are on the International Space Station when their countries go to Nuclear War with each other. Their last orders are to eliminate the other.",
"A treasure hunter finds a tomb buried beneath the dirt.",
"A young brother and sister find an old door in their basement that wasn’t there before.",
"Winged creatures can be seen within the storm clouds above.",
"A man wakes up to find a hobo clown staring down at him.",
"Residents of a town suddenly fall dead while the dead from cemeteries around them rise.",
"A doctor performs the first head transplant — things go wrong.",
" A man is texted pictures of himself in various stages of torture that he has no memory of.",
"A girl wakes up to find a little boy sitting on his bed, claiming to be her younger brother — but she never had one.",
" A scare walk in the woods during Halloween is actually real.",
"A bartender serves last call to the only remaining patron who is the Devil himself.",
" Earth suffers a planet-wide blackout as all technology is lost.",
" A boy’s stepfather is actually a murderous werewolf.",
"Something has turned the neighborhood pets into demonic killers.",
"A priest is a vampire.",
" A woman wakes up with no eyes.",
"A man wakes up with no mouth.",
"A monster is terrified by the scary child who lives above his bed.",
" An astronaut jettisoned into the cold of space in a mission gone wrong suddenly appears at the doorstep of his family.",
"A woman answers a phone call only to learn that the voice on the other end is her future self warning her that a killer is looming.",
"A boy realizes that his family has been replaced by aliens.",
"A woman wakes up in an abandoned prison that she cannot escape.",
" A bank robber steals from the small town bank that holds the riches of witches.",
"A door-to-door salesman circa the 1950s visits the wrong house.",
" Deceased soldiers return to their Civil War era homes.",
" Kidnappers abduct the child of a vampire.",
"An innocent circus clown discovers the dark history of the trade.",
"A homeless man is stalked by faceless beings.",
"A spelunker stumbles upon a series of caverns infested with rattlesnakes.",
"A group of friends are forced to venture through a chamber of horrors where only one is promised to survive.",
"He’s not the man she thought he was. In fact, he’s not a man at all.",
"Suburbia is actually purgatory.",
"Someone discovers that we are all actually robots — who created us and why?",
"She’s not an angel, she’s a demon.

",
" An old shipwreck washes ashore.",
"A sinkhole swallows a house whole and unleashes something from beneath.",
" A man suffers from sleep paralysis at the worst possible time.",
" A woman out hiking is caught in a bear trap as the sun begins to go down.",
"Naked figures with no faces stalk campers in the woods",
" An astronaut is the sole survivor of a moon landing gone wrong — only to discover that the moon is infested with strange creatures.",
"A woman is wrongfully condemned to an insane asylum.",
" A mother’s baby will not leave it’s womb and continues to grow and grow and grow while doctors try to cut it out but can’t.",
" Friends on a road trip stumble upon a back country town whose residents all dress up as different types of clowns.",
"Tourists in Ireland retreat to an old castle when the country is taken over by greedy and vengeful leprechauns.",
"A boy on a farm makes a scarecrow that comes alive.",
"A figure dressed in an old, dirty Easter Bunny suit haunts the children of a town.",
" The abused animals of a zoo are unleashed and wreak havoc on a small town.",
"A deceased grandma’s old doll collection comes alive.",
" Little Red Riding Hood was a vampire.",
"Somebody clones Hitler and raises him as a white supremacist.",
"A pumpkin patch comes alive — beings with heads of pumpkins and bodies of vines.",
"An endless swarm of killer bees wreaks havoc on the country.",
"An endless swarm of killer bees wreaks havoc on the country.",
"A natural anomaly brings all of the country’s spiders to a horrified town.",
"A woman finds old 16mm film from her childhood and sees that she had a sister — what happened to her?",
"Something ancient rises from an old pond",
". A woman suddenly begins to wake up in somebody else’s body every morning — each day ends with her being stocked and killed by the same murderer in black.",
"An Artificial Intelligence begins to communicate with a family online, only to terrorize them through their technology.",
"A family buys a cheap house only to discover that an old cemetery is their back yard.",
" Years after the zombie apocalypse subsides, survivors discover that the epidemic was caused by aliens that have appeared to lay claim to the plane",
" A woman has memories of being abducted by aliens — but she soon learns that they weren’t aliens. They were…",
" A boy has a tumor that slowly grows into a Siamese twin — the older they get, the more evil the twin becomes.",
"A cult that worships history’s deadliest serial killers begins to kill by copying their methods.",
"Stone gargoyles suddenly appear on the tops of buildings and houses of a small town.",
" A family on a boat trip stumbles upon an old pirate ship.",
"A winter snow storm traps a family in an abandoned insane asylum.",
"A little girl comes down from upstairs and asks her parents, “Can you hear it breathing? I can.”",
" A town is enveloped in unexplained darkness for weeks.",
"A jetliner flies high in the sky as Nuclear War breaks out below.",
" Children discover a deep, dark well in the woods — an old ladder leads down into it.",
"A child sleep walks into their parent’s room and whispers, “I’m sorry. The devil told me to.”",
"As a woman showers, a voice comes from the drain whispering, “I see you.”",
"A child finds a crayon drawing of a strange family — it’s inscribed with the words we live in your walls.",
"All of the cemetery’s graves are now open, gaping holes — the dirt pushed out from underground.",
"A woman is watching a scary movie alone on Halloween night — someone, or something, keeps knocking at her door.",
"Someone is taking a bath as a hand from behind the shower curtain pushes their head into the water.",
"A farmer and his sons begin to hear the laughter of children coming from his fields at night — no children are in sight.",
"Someone looks out their window to see a clown standing at a corner holding a balloon — staring them.",
"Mannequins in a department store seem to be moving on their own.",
"What if the God people worshiped was really Satan — and Satan had somehow kept God prisoner?",
"A man dies and wakes up in the body of a serial killer — and no matter how hard he tries to stop killing, he can’t.",
"A prisoner awakens to find the prison empty — but he’s locked in his cell.",
"A woman jogging stumbles upon a dead, bloody body — she then hears a strange clicking sound and looks up to see a dark figure running towards her.",
"A girl hears laughter downstairs — she’s the only one home.",
"An Uber driver picks up the wrong person — and may not live to tell the tale.",
"There’s someone or something living and moving up in the attic — but it’s not a ghost.",
". A child’s imaginary friend is not imaginary.",
]
